// import './StorageProvider';
import './HashProvider';
import './IdGeneratorProvider';
import './GalaxPayProvider';
// import './MailTemplateProvider';
// import './MailProvider';
// import './CodeGeneratorProvider';
// import './PushNotificationProvider';
// import './RepositoryUtilsProvider';
// import './PaymentProvider';
